<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Discount for low cost operations</name>
  <uuid>af449a4b-5fd8-4a66-a1a6-26ef80ebb4b1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Operation cost' is between 0 and 0.25
then
    add a new offer where
        the estimated cost is 0.1 * the usage , 
        the message is "Offer " + the name + " a 10% discount on his current subscription" to decision ;
else
    add a new offer where
        the estimated cost is 0.05 * the usage , 
        the message is "Offer " + the name + " a 5% discount on his current subscription" to decision ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
