<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>High discount</name>
  <uuid>a9c5d0ae-185d-4ec1-bd6a-0a45c735feb4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Upgrade policy' is undefined 
then
    add a new offer where
        the estimated cost is  0.2 * the usage, 
        the message is "Offer " + the name + " a 20% discount on his current subscription" to decision ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
