<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Upgrade</name>
  <uuid>de21a96b-39ef-41d7-8ea3-28b7808f6fcc</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    'Upgrade policy' is defined
then
    add a new offer where
        the estimated cost is  0.15 * the usage , 
        the message is "Upgrade " + the name + " to " + 'Upgrade policy' + " with a 15% discount."
     to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
