<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>c0b86a95-b1cf-4fd8-92cd-8896f9743588</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 20 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
