<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>age not valid</name>
  <uuid>f64d2361-40db-4132-b82c-ad73761fade9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
    set 'minAge' to 0;
    set 'maxAge' to 150;
if
  it is not true that the number of years between the birth date of Borrower and 'current time' is between minAge and maxAge
then
  decision does not get approved; 
  set the message of decision to "The borrower's age is not valid." ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
