<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>65c8e2fa-5b84-400f-8b6e-93523c156cee</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[decision gets approved; 
set the message of decision to "Congratulations! Your loan has been approved"  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
