<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>risky grade</name>
  <uuid>8d7d4db0-48ce-41d9-824d-1b9a842ee0a6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the grade of Grade is not one of { "A" , "B" , "C" }
then
    decision does not get approved; 
    set the message of decision to "We are sorry. Your loan has not been approved" ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
