<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>wrong SSN format</name>
  <uuid>1a866e90-8df0-4d81-b7c7-323a9cdb94be</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
    set 'area number' to 3 ;
    set 'group code' to 2 ;
    set 'serial number' to 4 ;
    set 'digits' to ( the length of the area number of the SSN of Borrower ) 
                            + ( the length of the group code of the SSN of Borrower ) 
                            + ( the length of the serial number of the SSN of Borrower ) ;
if
    any of the following conditions is true :
            - digits does not equal 9
            - the length of the area number of the SSN of Borrower does not equal 'area number'
            - the length of the group code of the SSN of Borrower does not equal 'group code'
            - the length of the serial number of the SSN of Borrower does not equal 'serial number'

then
   decision does not get approved; 
   set the message of decision to "The borrower's SSN should be formatted with 3-2-4 characters" ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
