<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Include operation cost</name>
  <uuid>1f35ff80-865f-4948-8d8e-89b8a4b8a323</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to decision * ( 1 - 'Operation cost' ) ;
print "Maximum retention budget: " + decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
