<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check error</name>
  <uuid>108f66af-22c3-45e8-98b8-436281600667</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
     'ML model invocation' is in error 
then
    set decision to 0.5 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
