<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>check error</name>
  <uuid>82a72484-ad55-4f39-9af7-0fe13b850266</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
   'ML model invocation' is in error 
then
    set decision to 1000 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
