<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Select best offer</name>
  <uuid>fb4b168c-b672-437a-a2c6-a4b6e3a0ea34</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
-- Loop on the ranked offers list and select the best one
set 'current offer' to an offer in 'Ranked retention offers' ;

-- Get the cost of the currently evaluated offer from the ranked list
set 'offer cost' to the estimated cost of 'current offer' ;

set 'maxBudget' to 20 ;

-- Select the best offer that is below the maximum retention budget

if 'offer cost' is less than maxBudget and
   'offer cost' is at least the estimated cost of decision 
   --the current evaluated offer is less expensive then the previously selected one
then
    -- select the current offer 
    set decision to 'current offer' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
